Close button trait
yiisoft/yii-bootstrap5 pull request #130
Opened 2023-11-02 13:36 UTC by Gerych1984

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ✔️

Since last PR I forgot about `Alert` and `Toast`, which have a close button but no toggle, `AbstractCloseButton` moved to `CloseButtonTrait`.

1. `Offcanvas` and `Modal` now extended from `AbstractToggleWidget`
2. `Offcanvas`, `Modal`, `Alert` and `Toast` now use `CloseButtonTrait`

2023-11-12 08:39 UTC, vjik requested changes

2023-11-12 08:39 UTC, vjik commented on src/CloseButtonTrait.php
> +    private bool $insideCloseButton = true;
```suggestion
    private bool $showCloseButton = true;
```

Seems, this name is more understandable.

2023-11-12 08:39 UTC, vjik commented on src/Alert.php
> +    public function toggleComponent(): string
```suggestion
    protected function toggleComponent(): string
```

2023-11-21 14:54 UTC, terabytesoftw approved these changes

2023-11-21 16:30 UTC, merged