Apply last changes in `Alert` widget.
yiisoft/yii-bootstrap5 pull request #164
Opened 2024-10-30 12:53 UTC by terabytesoftw

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌

2024-10-30 21:15 UTC, samdark requested changes

2024-10-30 21:15 UTC, samdark commented on src/Alert.php
> +     * @param string|null ...$value One or more CSS class names to add. Pass null to skip adding a class.
```suggestion
     * @param string|null ...$value One or more CSS class names to add. Pass `null` to skip adding a class.
```

2024-10-30 21:15 UTC, samdark commented on src/Alert.php
> +     * Adds a style class for the alert component.
```suggestion
     * Adds a CSS style for the alert component.
```

2024-10-30 21:15 UTC, samdark commented on src/Alert.php
> +     * @param array|string $value The style class for the alert component. If an array, the values will be separated by
```suggestion
     * @param array|string $value The CSS style for the alert component. If an array, the values will be separated by
```

2024-10-30 21:15 UTC, samdark commented on src/Alert.php
> +     * @return self A new instance with the specified style class value added.
```suggestion
     * @return self A new instance with the specified CSS style value added.
```

2024-10-30 21:15 UTC, samdark commented on src/Alert.php
> +     * @param string|null ...$value One or more CSS class names to set. Pass null to skip setting a class.
```suggestion
     * @param string|null ...$value One or more CSS class names to set. Pass `null` to skip setting a class.
```

2024-10-31 08:40 UTC, vjik approved these changes

2024-10-31 08:41 UTC, terabytesoftw commented on src/Alert.php
> +     * @param string|null ...$value One or more CSS class names to add. Pass null to skip adding a class.
done.

2024-10-31 08:41 UTC, terabytesoftw commented on src/Alert.php
> +     * Adds a style class for the alert component.
done.

2024-10-31 08:41 UTC, terabytesoftw commented on src/Alert.php
> +     * @param array|string $value The style class for the alert component. If an array, the values will be separated by
done.

2024-10-31 08:41 UTC, terabytesoftw commented on src/Alert.php
> +     * @return self A new instance with the specified style class value added.
done.

2024-10-31 08:41 UTC, terabytesoftw commented on src/Alert.php
> +     * @param string|null ...$value One or more CSS class names to set. Pass null to skip setting a class.
done.

2024-10-31 20:49 UTC, samdark approved these changes

2024-11-01 05:50 UTC, merged