Add TextColorBackground enum and corresponding tests.
yiisoft/yii-bootstrap5 pull request #180
Opened 2024-12-06 11:20 UTC by terabytesoftw

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ❌

2024-12-06 12:08 UTC, vjik requested changes

2024-12-06 12:08 UTC, vjik commented on src/Utility/TextColorBackground.php
> +enum TextColorBackground: string
```suggestion
enum TextBackgroundColor: string
```

2024-12-06 12:24 UTC, terabytesoftw commented on src/Utility/TextColorBackground.php
> +enum TextColorBackground: string
done.

2024-12-07 07:09 UTC, samdark approved these changes

2024-12-08 15:33 UTC, merged