Adopt new changes BS5
yiisoft/yii-bootstrap5 pull request #47
Opened 2021-05-07 19:34 UTC by terabytesoftw

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ❌

2021-05-08 20:38 UTC, samdark requested changes

2021-05-08 20:38 UTC, samdark commented on src/Accordion.php
> +     * parent container.
```suggestion
     * Add to remove the default background-color, some borders, and some rounded corners
     * to render accordions edge-to-edge with their parent container.
```

2021-05-08 20:38 UTC, samdark commented on src/Accordion.php
> +     * @return $this
```suggestion
     * @return self
```

2021-05-08 20:38 UTC, samdark commented on src/NavBar.php
> +     * is '/' will be used. You may set it to `` if you want to have no link at all.
```suggestion
     * The URL for the brand's hyperlink tag and will be used for the "href" attribute of the brand link. Default value
     * is "/". You may set it to empty string if you want no link at all.
```

2021-05-08 20:38 UTC, samdark commented on src/NavBar.php
> +    public function brandLink(string $value): self
I think it's still URL.

2021-05-08 20:38 UTC, samdark commented on tests/AssetTest.php
>      public function testAssetRegister(string $type, string $asset, ?string $depend = null): void
This test wasn't testing anything useful (it was testing that asset manager works and that's already tested) so I've removed it from master.

What is worth testing is the fact that widgets, when used, are registering expected assets.

2021-05-10 15:08 UTC, terabytesoftw commented on src/Accordion.php
> +     * parent container.
done.

2021-05-10 15:08 UTC, terabytesoftw commented on src/Accordion.php
> +     * @return $this
done.

2021-05-10 15:08 UTC, terabytesoftw commented on src/NavBar.php
> +     * is '/' will be used. You may set it to `` if you want to have no link at all.
done.

2021-05-13 09:17 UTC, samdark approved these changes

2021-05-13 09:21 UTC, merged

2021-05-13 09:21 UTC, samdark commented
👍