Set psalm error level to 2
yiisoft/yii-bootstrap5 pull request #91
Opened 2022-07-17 13:25 UTC by dood-

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ❌
| Fixed issues  | -

- Set psalm error level to 2
- Replace deprecated `attributes()` with `addAttributes()`

2022-07-18 09:16 UTC, WinterSilence commented
https://github.com/yiisoft/yii-bootstrap5/blob/fcbb4e1fcda8a3215fc8075935ef636b05762e63/src/Tabs.php#L381 `@param string|null $navId`

2022-07-20 11:20 UTC, vjik requested changes

2022-07-20 11:20 UTC, vjik commented on src/Dropdown.php
> +            ->addAttributes($options)
Change version Yii HTML in composer.json to `^2.5`

2022-07-20 12:07 UTC, vjik approved these changes

2022-07-21 09:47 UTC, merged